# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'FreeLibExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeLibExample
    pod 'FreeLib', :path => "../freelib/"

end
